"""Generated from spy_ssz/schemas.yaml; do not edit."""

from .. import projections
from ..ssz import Bitfield, SszObject

class SignedBeaconBlockFulu(SszObject):
    @property
    def message(self) -> projections.BeaconBlockFulu: ...
    @property
    def signature(self) -> bytes: ...

SignedBeaconBlockFuluMainnet = SignedBeaconBlockFulu

class SignedBeaconBlockFuluMinimal(SignedBeaconBlockFulu): ...
class SignedBeaconBlockFuluGnosis(SignedBeaconBlockFulu): ...

class AttestationFulu(SszObject):
    @property
    def aggregation_bits(self) -> Bitfield: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...
    @property
    def committee_bits(self) -> Bitfield: ...

AttestationFuluMainnet = AttestationFulu

class AttestationFuluMinimal(AttestationFulu): ...
class AttestationFuluGnosis(AttestationFulu): ...

class AttestationDataFulu(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def index(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def source(self) -> projections.Checkpoint: ...
    @property
    def target(self) -> projections.Checkpoint: ...

AttestationDataFuluMainnet = AttestationDataFulu

class AttestationDataFuluMinimal(AttestationDataFulu): ...
class AttestationDataFuluGnosis(AttestationDataFulu): ...

class AggregateAndProofFulu(SszObject):
    @property
    def aggregator_index(self) -> int: ...
    @property
    def aggregate(self) -> projections.AttestationFulu: ...
    @property
    def selection_proof(self) -> bytes: ...

AggregateAndProofFuluMainnet = AggregateAndProofFulu

class AggregateAndProofFuluMinimal(AggregateAndProofFulu): ...
class AggregateAndProofFuluGnosis(AggregateAndProofFulu): ...

class SyncCommitteeContributionFulu(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def subcommittee_index(self) -> int: ...
    @property
    def aggregation_bits(self) -> Bitfield: ...
    @property
    def signature(self) -> bytes: ...

SyncCommitteeContributionFuluMainnet = SyncCommitteeContributionFulu

class SyncCommitteeContributionFuluMinimal(SyncCommitteeContributionFulu): ...
class SyncCommitteeContributionFuluGnosis(SyncCommitteeContributionFulu): ...

class ContributionAndProofFulu(SszObject):
    @property
    def aggregator_index(self) -> int: ...
    @property
    def contribution(self) -> projections.SyncCommitteeContribution: ...
    @property
    def selection_proof(self) -> bytes: ...

ContributionAndProofFuluMainnet = ContributionAndProofFulu

class ContributionAndProofFuluMinimal(ContributionAndProofFulu): ...
class ContributionAndProofFuluGnosis(ContributionAndProofFulu): ...

class SingleAttestationFulu(SszObject):
    @property
    def committee_index(self) -> int: ...
    @property
    def attester_index(self) -> int: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...

SingleAttestationFuluMainnet = SingleAttestationFulu

class SingleAttestationFuluMinimal(SingleAttestationFulu): ...
class SingleAttestationFuluGnosis(SingleAttestationFulu): ...

class SyncCommitteeMessageFulu(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def validator_index(self) -> int: ...
    @property
    def signature(self) -> bytes: ...

SyncCommitteeMessageFuluMainnet = SyncCommitteeMessageFulu

class SyncCommitteeMessageFuluMinimal(SyncCommitteeMessageFulu): ...
class SyncCommitteeMessageFuluGnosis(SyncCommitteeMessageFulu): ...

class SignedAggregateAndProofFulu(SszObject):
    @property
    def message(self) -> projections.AggregateAndProofFulu: ...
    @property
    def signature(self) -> bytes: ...

SignedAggregateAndProofFuluMainnet = SignedAggregateAndProofFulu

class SignedAggregateAndProofFuluMinimal(SignedAggregateAndProofFulu): ...
class SignedAggregateAndProofFuluGnosis(SignedAggregateAndProofFulu): ...

class SignedContributionAndProofFulu(SszObject):
    @property
    def message(self) -> projections.ContributionAndProof: ...
    @property
    def signature(self) -> bytes: ...

SignedContributionAndProofFuluMainnet = SignedContributionAndProofFulu

class SignedContributionAndProofFuluMinimal(SignedContributionAndProofFulu): ...
class SignedContributionAndProofFuluGnosis(SignedContributionAndProofFulu): ...

class IndexedAttestationFulu(SszObject):
    @property
    def attesting_indices(self) -> tuple[int, ...]: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...

IndexedAttestationFuluMainnet = IndexedAttestationFulu

class IndexedAttestationFuluMinimal(IndexedAttestationFulu): ...
class IndexedAttestationFuluGnosis(IndexedAttestationFulu): ...

class AttesterSlashingFulu(SszObject):
    @property
    def attestation_1(self) -> projections.IndexedAttestationFulu: ...
    @property
    def attestation_2(self) -> projections.IndexedAttestationFulu: ...

AttesterSlashingFuluMainnet = AttesterSlashingFulu

class AttesterSlashingFuluMinimal(AttesterSlashingFulu): ...
class AttesterSlashingFuluGnosis(AttesterSlashingFulu): ...

class BeaconBlockHeaderFulu(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def proposer_index(self) -> int: ...
    @property
    def parent_root(self) -> bytes: ...
    @property
    def state_root(self) -> bytes: ...
    @property
    def body_root(self) -> bytes: ...

BeaconBlockHeaderFuluMainnet = BeaconBlockHeaderFulu

class BeaconBlockHeaderFuluMinimal(BeaconBlockHeaderFulu): ...
class BeaconBlockHeaderFuluGnosis(BeaconBlockHeaderFulu): ...

class SignedBeaconBlockHeaderFulu(SszObject):
    @property
    def message(self) -> projections.BeaconBlockHeader: ...
    @property
    def signature(self) -> bytes: ...

SignedBeaconBlockHeaderFuluMainnet = SignedBeaconBlockHeaderFulu

class SignedBeaconBlockHeaderFuluMinimal(SignedBeaconBlockHeaderFulu): ...
class SignedBeaconBlockHeaderFuluGnosis(SignedBeaconBlockHeaderFulu): ...

class ProposerSlashingFulu(SszObject):
    @property
    def signed_header_1(self) -> projections.SignedBeaconBlockHeader: ...
    @property
    def signed_header_2(self) -> projections.SignedBeaconBlockHeader: ...

ProposerSlashingFuluMainnet = ProposerSlashingFulu

class ProposerSlashingFuluMinimal(ProposerSlashingFulu): ...
class ProposerSlashingFuluGnosis(ProposerSlashingFulu): ...

class BeaconBlockContentsFulu(SszObject):
    def header_dict(self) -> dict[str, str]: ...
    def block_hash_tree_root(self) -> str: ...
    def sign(self, signature: str | bytes) -> SignedBeaconBlockContentsFulu: ...
    @classmethod
    def signed_type(cls) -> type[SignedBeaconBlockContentsFulu]: ...

class SignedBeaconBlockContentsFulu(SszObject): ...

class BlindedBeaconBlockFulu(SszObject):
    def header_dict(self) -> dict[str, str]: ...
    def block_hash_tree_root(self) -> str: ...
    def sign(self, signature: str | bytes) -> SignedBlindedBeaconBlockFulu: ...
    @classmethod
    def signed_type(cls) -> type[SignedBlindedBeaconBlockFulu]: ...

class SignedBlindedBeaconBlockFulu(SszObject): ...
class SignedBeaconBlockContentsFuluMainnet(SignedBeaconBlockContentsFulu): ...

class BeaconBlockContentsFuluMainnet(BeaconBlockContentsFulu):
    def sign(self, signature: str | bytes) -> SignedBeaconBlockContentsFuluMainnet: ...
    @classmethod
    def signed_type(cls) -> type[SignedBeaconBlockContentsFuluMainnet]: ...

class SignedBlindedBeaconBlockFuluMainnet(SignedBlindedBeaconBlockFulu): ...

class BlindedBeaconBlockFuluMainnet(BlindedBeaconBlockFulu):
    def sign(self, signature: str | bytes) -> SignedBlindedBeaconBlockFuluMainnet: ...
    @classmethod
    def signed_type(cls) -> type[SignedBlindedBeaconBlockFuluMainnet]: ...

class SignedBeaconBlockContentsFuluMinimal(SignedBeaconBlockContentsFulu): ...

class BeaconBlockContentsFuluMinimal(BeaconBlockContentsFulu):
    def sign(self, signature: str | bytes) -> SignedBeaconBlockContentsFuluMinimal: ...
    @classmethod
    def signed_type(cls) -> type[SignedBeaconBlockContentsFuluMinimal]: ...

class SignedBlindedBeaconBlockFuluMinimal(SignedBlindedBeaconBlockFulu): ...

class BlindedBeaconBlockFuluMinimal(BlindedBeaconBlockFulu):
    def sign(self, signature: str | bytes) -> SignedBlindedBeaconBlockFuluMinimal: ...
    @classmethod
    def signed_type(cls) -> type[SignedBlindedBeaconBlockFuluMinimal]: ...

class SignedBeaconBlockContentsFuluGnosis(SignedBeaconBlockContentsFulu): ...

class BeaconBlockContentsFuluGnosis(BeaconBlockContentsFulu):
    def sign(self, signature: str | bytes) -> SignedBeaconBlockContentsFuluGnosis: ...
    @classmethod
    def signed_type(cls) -> type[SignedBeaconBlockContentsFuluGnosis]: ...

class SignedBlindedBeaconBlockFuluGnosis(SignedBlindedBeaconBlockFulu): ...

class BlindedBeaconBlockFuluGnosis(BlindedBeaconBlockFulu):
    def sign(self, signature: str | bytes) -> SignedBlindedBeaconBlockFuluGnosis: ...
    @classmethod
    def signed_type(cls) -> type[SignedBlindedBeaconBlockFuluGnosis]: ...
