"""Generated from spy_ssz/schemas.yaml; do not edit."""

from .. import projections
from ..ssz import Bitfield, SszObject

class FuluSignedBeaconBlock(SszObject):
    @property
    def message(self) -> projections.BeaconBlock: ...
    @property
    def signature(self) -> bytes: ...

FuluSignedBeaconBlockMainnet = FuluSignedBeaconBlock

class FuluSignedBeaconBlockMinimal(FuluSignedBeaconBlock): ...
class FuluSignedBeaconBlockGnosis(FuluSignedBeaconBlock): ...

class FuluAttestation(SszObject):
    @property
    def aggregation_bits(self) -> Bitfield: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...
    @property
    def committee_bits(self) -> Bitfield: ...

FuluAttestationMainnet = FuluAttestation

class FuluAttestationMinimal(FuluAttestation): ...
class FuluAttestationGnosis(FuluAttestation): ...

class FuluAttestationData(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def index(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def source(self) -> projections.Checkpoint: ...
    @property
    def target(self) -> projections.Checkpoint: ...

FuluAttestationDataMainnet = FuluAttestationData

class FuluAttestationDataMinimal(FuluAttestationData): ...
class FuluAttestationDataGnosis(FuluAttestationData): ...

class FuluAggregateAndProof(SszObject):
    @property
    def aggregator_index(self) -> int: ...
    @property
    def aggregate(self) -> projections.Attestation: ...
    @property
    def selection_proof(self) -> bytes: ...

FuluAggregateAndProofMainnet = FuluAggregateAndProof

class FuluAggregateAndProofMinimal(FuluAggregateAndProof): ...
class FuluAggregateAndProofGnosis(FuluAggregateAndProof): ...

class FuluSyncCommitteeContribution(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def subcommittee_index(self) -> int: ...
    @property
    def aggregation_bits(self) -> Bitfield: ...
    @property
    def signature(self) -> bytes: ...

FuluSyncCommitteeContributionMainnet = FuluSyncCommitteeContribution

class FuluSyncCommitteeContributionMinimal(FuluSyncCommitteeContribution): ...
class FuluSyncCommitteeContributionGnosis(FuluSyncCommitteeContribution): ...

class FuluContributionAndProof(SszObject):
    @property
    def aggregator_index(self) -> int: ...
    @property
    def contribution(self) -> projections.SyncCommitteeContribution: ...
    @property
    def selection_proof(self) -> bytes: ...

FuluContributionAndProofMainnet = FuluContributionAndProof

class FuluContributionAndProofMinimal(FuluContributionAndProof): ...
class FuluContributionAndProofGnosis(FuluContributionAndProof): ...

class FuluSingleAttestation(SszObject):
    @property
    def committee_index(self) -> int: ...
    @property
    def attester_index(self) -> int: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...

FuluSingleAttestationMainnet = FuluSingleAttestation

class FuluSingleAttestationMinimal(FuluSingleAttestation): ...
class FuluSingleAttestationGnosis(FuluSingleAttestation): ...

class FuluSyncCommitteeMessage(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def validator_index(self) -> int: ...
    @property
    def signature(self) -> bytes: ...

FuluSyncCommitteeMessageMainnet = FuluSyncCommitteeMessage

class FuluSyncCommitteeMessageMinimal(FuluSyncCommitteeMessage): ...
class FuluSyncCommitteeMessageGnosis(FuluSyncCommitteeMessage): ...

class FuluSignedAggregateAndProof(SszObject):
    @property
    def message(self) -> projections.AggregateAndProof: ...
    @property
    def signature(self) -> bytes: ...

FuluSignedAggregateAndProofMainnet = FuluSignedAggregateAndProof

class FuluSignedAggregateAndProofMinimal(FuluSignedAggregateAndProof): ...
class FuluSignedAggregateAndProofGnosis(FuluSignedAggregateAndProof): ...

class FuluSignedContributionAndProof(SszObject):
    @property
    def message(self) -> projections.ContributionAndProof: ...
    @property
    def signature(self) -> bytes: ...

FuluSignedContributionAndProofMainnet = FuluSignedContributionAndProof

class FuluSignedContributionAndProofMinimal(FuluSignedContributionAndProof): ...
class FuluSignedContributionAndProofGnosis(FuluSignedContributionAndProof): ...

class FuluIndexedAttestation(SszObject):
    @property
    def attesting_indices(self) -> tuple[int, ...]: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...

FuluIndexedAttestationMainnet = FuluIndexedAttestation

class FuluIndexedAttestationMinimal(FuluIndexedAttestation): ...
class FuluIndexedAttestationGnosis(FuluIndexedAttestation): ...

class FuluAttesterSlashing(SszObject):
    @property
    def attestation_1(self) -> projections.IndexedAttestation: ...
    @property
    def attestation_2(self) -> projections.IndexedAttestation: ...

FuluAttesterSlashingMainnet = FuluAttesterSlashing

class FuluAttesterSlashingMinimal(FuluAttesterSlashing): ...
class FuluAttesterSlashingGnosis(FuluAttesterSlashing): ...

class FuluBeaconBlockHeader(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def proposer_index(self) -> int: ...
    @property
    def parent_root(self) -> bytes: ...
    @property
    def state_root(self) -> bytes: ...
    @property
    def body_root(self) -> bytes: ...

FuluBeaconBlockHeaderMainnet = FuluBeaconBlockHeader

class FuluBeaconBlockHeaderMinimal(FuluBeaconBlockHeader): ...
class FuluBeaconBlockHeaderGnosis(FuluBeaconBlockHeader): ...

class FuluSignedBeaconBlockHeader(SszObject):
    @property
    def message(self) -> projections.BeaconBlockHeader: ...
    @property
    def signature(self) -> bytes: ...

FuluSignedBeaconBlockHeaderMainnet = FuluSignedBeaconBlockHeader

class FuluSignedBeaconBlockHeaderMinimal(FuluSignedBeaconBlockHeader): ...
class FuluSignedBeaconBlockHeaderGnosis(FuluSignedBeaconBlockHeader): ...

class FuluProposerSlashing(SszObject):
    @property
    def signed_header_1(self) -> projections.SignedBeaconBlockHeader: ...
    @property
    def signed_header_2(self) -> projections.SignedBeaconBlockHeader: ...

FuluProposerSlashingMainnet = FuluProposerSlashing

class FuluProposerSlashingMinimal(FuluProposerSlashing): ...
class FuluProposerSlashingGnosis(FuluProposerSlashing): ...

class FuluBeaconBlockContents(SszObject):
    def header_dict(self) -> dict[str, str]: ...
    def block_hash_tree_root(self) -> str: ...
    def sign(self, signature: str | bytes) -> FuluSignedBeaconBlockContents: ...
    @classmethod
    def signed_type(cls) -> type[FuluSignedBeaconBlockContents]: ...

class FuluSignedBeaconBlockContents(SszObject): ...

class FuluBlindedBeaconBlock(SszObject):
    def header_dict(self) -> dict[str, str]: ...
    def block_hash_tree_root(self) -> str: ...
    def sign(self, signature: str | bytes) -> FuluSignedBlindedBeaconBlock: ...
    @classmethod
    def signed_type(cls) -> type[FuluSignedBlindedBeaconBlock]: ...

class FuluSignedBlindedBeaconBlock(SszObject): ...
class FuluSignedBeaconBlockContentsMainnet(FuluSignedBeaconBlockContents): ...

class FuluBeaconBlockContentsMainnet(FuluBeaconBlockContents):
    def sign(self, signature: str | bytes) -> FuluSignedBeaconBlockContentsMainnet: ...
    @classmethod
    def signed_type(cls) -> type[FuluSignedBeaconBlockContentsMainnet]: ...

class FuluSignedBlindedBeaconBlockMainnet(FuluSignedBlindedBeaconBlock): ...

class FuluBlindedBeaconBlockMainnet(FuluBlindedBeaconBlock):
    def sign(self, signature: str | bytes) -> FuluSignedBlindedBeaconBlockMainnet: ...
    @classmethod
    def signed_type(cls) -> type[FuluSignedBlindedBeaconBlockMainnet]: ...

class FuluSignedBeaconBlockContentsMinimal(FuluSignedBeaconBlockContents): ...

class FuluBeaconBlockContentsMinimal(FuluBeaconBlockContents):
    def sign(self, signature: str | bytes) -> FuluSignedBeaconBlockContentsMinimal: ...
    @classmethod
    def signed_type(cls) -> type[FuluSignedBeaconBlockContentsMinimal]: ...

class FuluSignedBlindedBeaconBlockMinimal(FuluSignedBlindedBeaconBlock): ...

class FuluBlindedBeaconBlockMinimal(FuluBlindedBeaconBlock):
    def sign(self, signature: str | bytes) -> FuluSignedBlindedBeaconBlockMinimal: ...
    @classmethod
    def signed_type(cls) -> type[FuluSignedBlindedBeaconBlockMinimal]: ...

class FuluSignedBeaconBlockContentsGnosis(FuluSignedBeaconBlockContents): ...

class FuluBeaconBlockContentsGnosis(FuluBeaconBlockContents):
    def sign(self, signature: str | bytes) -> FuluSignedBeaconBlockContentsGnosis: ...
    @classmethod
    def signed_type(cls) -> type[FuluSignedBeaconBlockContentsGnosis]: ...

class FuluSignedBlindedBeaconBlockGnosis(FuluSignedBlindedBeaconBlock): ...

class FuluBlindedBeaconBlockGnosis(FuluBlindedBeaconBlock):
    def sign(self, signature: str | bytes) -> FuluSignedBlindedBeaconBlockGnosis: ...
    @classmethod
    def signed_type(cls) -> type[FuluSignedBlindedBeaconBlockGnosis]: ...
