"""Generated from spy_ssz/schemas.yaml; do not edit."""

from enum import IntEnum


class Fork(IntEnum):
    PHASE0 = 0
    ALTAIR = 1
    BELLATRIX = 2
    CAPELLA = 3
    DENEB = 4
    ELECTRA = 5
    FULU = 6
    GLOAS = 7


class ObjectKind(IntEnum):
    SIGNED_BEACON_BLOCK = 1
    BEACON_BLOCK = 2
    ATTESTATION = 3
    ATTESTATION_DATA = 4
    AGGREGATE_AND_PROOF = 5
    SYNC_COMMITTEE_CONTRIBUTION = 6
    CONTRIBUTION_AND_PROOF = 7
    BEACON_BLOCK_CONTENTS = 8
    SIGNED_BEACON_BLOCK_CONTENTS = 9
    BLINDED_BEACON_BLOCK = 10
    SIGNED_BLINDED_BEACON_BLOCK = 11
    SINGLE_ATTESTATION = 12
    SYNC_COMMITTEE_MESSAGE = 13
    SIGNED_AGGREGATE_AND_PROOF = 14
    SIGNED_CONTRIBUTION_AND_PROOF = 15
    INDEXED_ATTESTATION = 16
    ATTESTER_SLASHING = 17
    BEACON_BLOCK_HEADER = 18
    SIGNED_BEACON_BLOCK_HEADER = 19
    PROPOSER_SLASHING = 20
    PAYLOAD_ATTESTATION_DATA = 21
    PAYLOAD_ATTESTATION = 22
    PAYLOAD_ATTESTATION_MESSAGE = 23
    PROPOSER_PREFERENCES = 24
    SIGNED_PROPOSER_PREFERENCES = 25
