"""Generated immutable projections from consensus_types.json; do not edit."""

from typing import Any

from ._schema_enums import Fork

class Projection:
    def to_obj(self) -> dict[str, Any]: ...

def project_value(fork: Fork, type_id: int, value: Any) -> Any: ...
def project_field(fork: Fork, consensus_type: str, name: str, value: Any) -> Any: ...

class AggregateAndProof(Projection):
    @property
    def aggregator_index(self) -> int: ...
    @property
    def aggregate(self) -> ElectraAttestation: ...
    @property
    def selection_proof(self) -> bytes: ...

class AttestationData(Projection):
    @property
    def slot(self) -> int: ...
    @property
    def index(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def source(self) -> Checkpoint: ...
    @property
    def target(self) -> Checkpoint: ...

class AttesterSlashing(Projection):
    @property
    def attestation_1(self) -> IndexedAttestation: ...
    @property
    def attestation_2(self) -> IndexedAttestation: ...

class BLSToExecutionChange(Projection):
    @property
    def validator_index(self) -> int: ...
    @property
    def from_bls_pubkey(self) -> bytes: ...
    @property
    def to_execution_address(self) -> bytes: ...

class BeaconBlock(Projection):
    @property
    def slot(self) -> int: ...
    @property
    def proposer_index(self) -> int: ...
    @property
    def parent_root(self) -> bytes: ...
    @property
    def state_root(self) -> bytes: ...
    @property
    def body(self) -> BeaconBlockBody: ...

class BeaconBlockBody(Projection):
    @property
    def randao_reveal(self) -> bytes: ...
    @property
    def eth1_data(self) -> Eth1Data: ...
    @property
    def graffiti(self) -> bytes: ...
    @property
    def proposer_slashings(self) -> tuple[ProposerSlashing, ...]: ...
    @property
    def attester_slashings(self) -> tuple[AttesterSlashing, ...]: ...
    @property
    def attestations(self) -> tuple[ElectraAttestation, ...]: ...
    @property
    def deposits(self) -> tuple[Deposit, ...]: ...
    @property
    def voluntary_exits(self) -> tuple[SignedVoluntaryExit, ...]: ...
    @property
    def sync_aggregate(self) -> SyncAggregate: ...
    @property
    def execution_payload(self) -> ExecutionPayload: ...
    @property
    def bls_to_execution_changes(self) -> tuple[SignedBLSToExecutionChange, ...]: ...
    @property
    def blob_kzg_commitments(self) -> tuple[bytes, ...]: ...
    @property
    def execution_requests(self) -> ExecutionRequests: ...

class BeaconBlockHeader(Projection):
    @property
    def slot(self) -> int: ...
    @property
    def proposer_index(self) -> int: ...
    @property
    def parent_root(self) -> bytes: ...
    @property
    def state_root(self) -> bytes: ...
    @property
    def body_root(self) -> bytes: ...

class Checkpoint(Projection):
    @property
    def epoch(self) -> int: ...
    @property
    def root(self) -> bytes: ...

class ConsolidationRequest(Projection):
    @property
    def source_address(self) -> bytes: ...
    @property
    def source_pubkey(self) -> bytes: ...
    @property
    def target_pubkey(self) -> bytes: ...

class ContributionAndProof(Projection):
    @property
    def aggregator_index(self) -> int: ...
    @property
    def contribution(self) -> SyncCommitteeContribution: ...
    @property
    def selection_proof(self) -> bytes: ...

class Deposit(Projection):
    @property
    def proof(self) -> tuple[bytes, ...]: ...
    @property
    def data(self) -> DepositData: ...

class DepositData(Projection):
    @property
    def pubkey(self) -> bytes: ...
    @property
    def withdrawal_credentials(self) -> bytes: ...
    @property
    def amount(self) -> int: ...
    @property
    def signature(self) -> bytes: ...

class DepositRequest(Projection):
    @property
    def pubkey(self) -> bytes: ...
    @property
    def withdrawal_credentials(self) -> bytes: ...
    @property
    def amount(self) -> int: ...
    @property
    def signature(self) -> bytes: ...
    @property
    def index(self) -> int: ...

class ElectraAttestation(Projection):
    @property
    def aggregation_bits(self) -> bytes: ...
    @property
    def data(self) -> AttestationData: ...
    @property
    def signature(self) -> bytes: ...
    @property
    def committee_bits(self) -> bytes: ...

class Eth1Data(Projection):
    @property
    def deposit_root(self) -> bytes: ...
    @property
    def deposit_count(self) -> int: ...
    @property
    def block_hash(self) -> bytes: ...

class ExecutionPayload(Projection):
    @property
    def parent_hash(self) -> bytes: ...
    @property
    def fee_recipient(self) -> bytes: ...
    @property
    def state_root(self) -> bytes: ...
    @property
    def receipts_root(self) -> bytes: ...
    @property
    def logs_bloom(self) -> bytes: ...
    @property
    def prev_randao(self) -> bytes: ...
    @property
    def block_number(self) -> int: ...
    @property
    def gas_limit(self) -> int: ...
    @property
    def gas_used(self) -> int: ...
    @property
    def timestamp(self) -> int: ...
    @property
    def extra_data(self) -> bytes: ...
    @property
    def base_fee_per_gas(self) -> int: ...
    @property
    def block_hash(self) -> bytes: ...
    @property
    def transactions(self) -> tuple[bytes, ...]: ...
    @property
    def withdrawals(self) -> tuple[Withdrawal, ...]: ...
    @property
    def blob_gas_used(self) -> int: ...
    @property
    def excess_blob_gas(self) -> int: ...

class ExecutionRequests(Projection):
    @property
    def deposits(self) -> tuple[DepositRequest, ...]: ...
    @property
    def withdrawals(self) -> tuple[WithdrawalRequest, ...]: ...
    @property
    def consolidations(self) -> tuple[ConsolidationRequest, ...]: ...

class FuluAttestation(Projection):
    @property
    def aggregation_bits(self) -> bytes: ...
    @property
    def data(self) -> AttestationData: ...
    @property
    def signature(self) -> bytes: ...
    @property
    def committee_bits(self) -> bytes: ...

class GloasAttestation(Projection):
    @property
    def aggregation_bits(self) -> bytes: ...
    @property
    def data(self) -> AttestationData: ...
    @property
    def signature(self) -> bytes: ...
    @property
    def committee_bits(self) -> bytes: ...

class IndexedAttestation(Projection):
    @property
    def attesting_indices(self) -> tuple[int, ...]: ...
    @property
    def data(self) -> AttestationData: ...
    @property
    def signature(self) -> bytes: ...

class ProposerSlashing(Projection):
    @property
    def signed_header_1(self) -> SignedBeaconBlockHeader: ...
    @property
    def signed_header_2(self) -> SignedBeaconBlockHeader: ...

class SignedBLSToExecutionChange(Projection):
    @property
    def message(self) -> BLSToExecutionChange: ...
    @property
    def signature(self) -> bytes: ...

class SignedBeaconBlock(Projection):
    @property
    def message(self) -> BeaconBlock: ...
    @property
    def signature(self) -> bytes: ...

class SignedBeaconBlockHeader(Projection):
    @property
    def message(self) -> BeaconBlockHeader: ...
    @property
    def signature(self) -> bytes: ...

class SignedVoluntaryExit(Projection):
    @property
    def message(self) -> VoluntaryExit: ...
    @property
    def signature(self) -> bytes: ...

class SyncAggregate(Projection):
    @property
    def sync_committee_bits(self) -> bytes: ...
    @property
    def sync_committee_signature(self) -> bytes: ...

class SyncCommitteeContribution(Projection):
    @property
    def slot(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def subcommittee_index(self) -> int: ...
    @property
    def aggregation_bits(self) -> bytes: ...
    @property
    def signature(self) -> bytes: ...

class VoluntaryExit(Projection):
    @property
    def epoch(self) -> int: ...
    @property
    def validator_index(self) -> int: ...

class Withdrawal(Projection):
    @property
    def index(self) -> int: ...
    @property
    def validator_index(self) -> int: ...
    @property
    def address(self) -> bytes: ...
    @property
    def amount(self) -> int: ...

class WithdrawalRequest(Projection):
    @property
    def source_address(self) -> bytes: ...
    @property
    def validator_pubkey(self) -> bytes: ...
    @property
    def amount(self) -> int: ...
