"""Generated from spy_ssz/schemas.yaml; do not edit."""

from . import projections
from .ssz import Bitfield, SszObject

class AttestationElectra(SszObject):
    @property
    def aggregation_bits(self) -> Bitfield: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...
    @property
    def committee_bits(self) -> Bitfield: ...

AttestationElectraMainnet = AttestationElectra

class AttestationElectraMinimal(AttestationElectra): ...
class AttestationElectraGnosis(AttestationElectra): ...

class AttestationDataElectra(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def index(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def source(self) -> projections.Checkpoint: ...
    @property
    def target(self) -> projections.Checkpoint: ...

AttestationDataElectraMainnet = AttestationDataElectra

class AttestationDataElectraMinimal(AttestationDataElectra): ...
class AttestationDataElectraGnosis(AttestationDataElectra): ...

class AggregateAndProofElectra(SszObject):
    @property
    def aggregator_index(self) -> int: ...
    @property
    def aggregate(self) -> projections.AttestationElectra: ...
    @property
    def selection_proof(self) -> bytes: ...

AggregateAndProofElectraMainnet = AggregateAndProofElectra

class AggregateAndProofElectraMinimal(AggregateAndProofElectra): ...
class AggregateAndProofElectraGnosis(AggregateAndProofElectra): ...

class SyncCommitteeContributionElectra(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def subcommittee_index(self) -> int: ...
    @property
    def aggregation_bits(self) -> Bitfield: ...
    @property
    def signature(self) -> bytes: ...

SyncCommitteeContributionElectraMainnet = SyncCommitteeContributionElectra

class SyncCommitteeContributionElectraMinimal(SyncCommitteeContributionElectra): ...
class SyncCommitteeContributionElectraGnosis(SyncCommitteeContributionElectra): ...

class ContributionAndProofElectra(SszObject):
    @property
    def aggregator_index(self) -> int: ...
    @property
    def contribution(self) -> projections.SyncCommitteeContribution: ...
    @property
    def selection_proof(self) -> bytes: ...

ContributionAndProofElectraMainnet = ContributionAndProofElectra

class ContributionAndProofElectraMinimal(ContributionAndProofElectra): ...
class ContributionAndProofElectraGnosis(ContributionAndProofElectra): ...

class SingleAttestationElectra(SszObject):
    @property
    def committee_index(self) -> int: ...
    @property
    def attester_index(self) -> int: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...

SingleAttestationElectraMainnet = SingleAttestationElectra

class SingleAttestationElectraMinimal(SingleAttestationElectra): ...
class SingleAttestationElectraGnosis(SingleAttestationElectra): ...

class SyncCommitteeMessageElectra(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def validator_index(self) -> int: ...
    @property
    def signature(self) -> bytes: ...

SyncCommitteeMessageElectraMainnet = SyncCommitteeMessageElectra

class SyncCommitteeMessageElectraMinimal(SyncCommitteeMessageElectra): ...
class SyncCommitteeMessageElectraGnosis(SyncCommitteeMessageElectra): ...

class SignedAggregateAndProofElectra(SszObject):
    @property
    def message(self) -> projections.AggregateAndProofElectra: ...
    @property
    def signature(self) -> bytes: ...

SignedAggregateAndProofElectraMainnet = SignedAggregateAndProofElectra

class SignedAggregateAndProofElectraMinimal(SignedAggregateAndProofElectra): ...
class SignedAggregateAndProofElectraGnosis(SignedAggregateAndProofElectra): ...

class SignedContributionAndProofElectra(SszObject):
    @property
    def message(self) -> projections.ContributionAndProof: ...
    @property
    def signature(self) -> bytes: ...

SignedContributionAndProofElectraMainnet = SignedContributionAndProofElectra

class SignedContributionAndProofElectraMinimal(SignedContributionAndProofElectra): ...
class SignedContributionAndProofElectraGnosis(SignedContributionAndProofElectra): ...

class IndexedAttestationElectra(SszObject):
    @property
    def attesting_indices(self) -> tuple[int, ...]: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...

IndexedAttestationElectraMainnet = IndexedAttestationElectra

class IndexedAttestationElectraMinimal(IndexedAttestationElectra): ...
class IndexedAttestationElectraGnosis(IndexedAttestationElectra): ...

class AttesterSlashingElectra(SszObject):
    @property
    def attestation_1(self) -> projections.IndexedAttestationElectra: ...
    @property
    def attestation_2(self) -> projections.IndexedAttestationElectra: ...

AttesterSlashingElectraMainnet = AttesterSlashingElectra

class AttesterSlashingElectraMinimal(AttesterSlashingElectra): ...
class AttesterSlashingElectraGnosis(AttesterSlashingElectra): ...

class BeaconBlockHeaderElectra(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def proposer_index(self) -> int: ...
    @property
    def parent_root(self) -> bytes: ...
    @property
    def state_root(self) -> bytes: ...
    @property
    def body_root(self) -> bytes: ...

BeaconBlockHeaderElectraMainnet = BeaconBlockHeaderElectra

class BeaconBlockHeaderElectraMinimal(BeaconBlockHeaderElectra): ...
class BeaconBlockHeaderElectraGnosis(BeaconBlockHeaderElectra): ...

class SignedBeaconBlockHeaderElectra(SszObject):
    @property
    def message(self) -> projections.BeaconBlockHeader: ...
    @property
    def signature(self) -> bytes: ...

SignedBeaconBlockHeaderElectraMainnet = SignedBeaconBlockHeaderElectra

class SignedBeaconBlockHeaderElectraMinimal(SignedBeaconBlockHeaderElectra): ...
class SignedBeaconBlockHeaderElectraGnosis(SignedBeaconBlockHeaderElectra): ...

class ProposerSlashingElectra(SszObject):
    @property
    def signed_header_1(self) -> projections.SignedBeaconBlockHeader: ...
    @property
    def signed_header_2(self) -> projections.SignedBeaconBlockHeader: ...

ProposerSlashingElectraMainnet = ProposerSlashingElectra

class ProposerSlashingElectraMinimal(ProposerSlashingElectra): ...
class ProposerSlashingElectraGnosis(ProposerSlashingElectra): ...
