"""Generated from spy_ssz/schemas.yaml; do not edit."""

from .ssz import SszObject

class Attestation(SszObject): ...

AttestationMainnet = Attestation

class AttestationMinimal(Attestation): ...
class AttestationGnosis(Attestation): ...
class AttestationData(SszObject): ...

AttestationDataMainnet = AttestationData

class AttestationDataMinimal(AttestationData): ...
class AttestationDataGnosis(AttestationData): ...
class AggregateAndProof(SszObject): ...

AggregateAndProofMainnet = AggregateAndProof

class AggregateAndProofMinimal(AggregateAndProof): ...
class AggregateAndProofGnosis(AggregateAndProof): ...
class SyncCommitteeContribution(SszObject): ...

SyncCommitteeContributionMainnet = SyncCommitteeContribution

class SyncCommitteeContributionMinimal(SyncCommitteeContribution): ...
class SyncCommitteeContributionGnosis(SyncCommitteeContribution): ...
class ContributionAndProof(SszObject): ...

ContributionAndProofMainnet = ContributionAndProof

class ContributionAndProofMinimal(ContributionAndProof): ...
class ContributionAndProofGnosis(ContributionAndProof): ...
