"""Generated from spy_ssz/schemas.yaml; do not edit."""

from . import projections
from .ssz import Bitfield, SszObject

class Attestation(SszObject):
    @property
    def aggregation_bits(self) -> Bitfield: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...
    @property
    def committee_bits(self) -> Bitfield: ...

AttestationMainnet = Attestation

class AttestationMinimal(Attestation): ...
class AttestationGnosis(Attestation): ...

class AttestationData(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def index(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def source(self) -> projections.Checkpoint: ...
    @property
    def target(self) -> projections.Checkpoint: ...

AttestationDataMainnet = AttestationData

class AttestationDataMinimal(AttestationData): ...
class AttestationDataGnosis(AttestationData): ...

class AggregateAndProof(SszObject):
    @property
    def aggregator_index(self) -> int: ...
    @property
    def aggregate(self) -> projections.ElectraAttestation: ...
    @property
    def selection_proof(self) -> bytes: ...

AggregateAndProofMainnet = AggregateAndProof

class AggregateAndProofMinimal(AggregateAndProof): ...
class AggregateAndProofGnosis(AggregateAndProof): ...

class SyncCommitteeContribution(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def subcommittee_index(self) -> int: ...
    @property
    def aggregation_bits(self) -> Bitfield: ...
    @property
    def signature(self) -> bytes: ...

SyncCommitteeContributionMainnet = SyncCommitteeContribution

class SyncCommitteeContributionMinimal(SyncCommitteeContribution): ...
class SyncCommitteeContributionGnosis(SyncCommitteeContribution): ...

class ContributionAndProof(SszObject):
    @property
    def aggregator_index(self) -> int: ...
    @property
    def contribution(self) -> projections.SyncCommitteeContribution: ...
    @property
    def selection_proof(self) -> bytes: ...

ContributionAndProofMainnet = ContributionAndProof

class ContributionAndProofMinimal(ContributionAndProof): ...
class ContributionAndProofGnosis(ContributionAndProof): ...

class SingleAttestation(SszObject):
    @property
    def committee_index(self) -> int: ...
    @property
    def attester_index(self) -> int: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...

SingleAttestationMainnet = SingleAttestation

class SingleAttestationMinimal(SingleAttestation): ...
class SingleAttestationGnosis(SingleAttestation): ...

class SyncCommitteeMessage(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def validator_index(self) -> int: ...
    @property
    def signature(self) -> bytes: ...

SyncCommitteeMessageMainnet = SyncCommitteeMessage

class SyncCommitteeMessageMinimal(SyncCommitteeMessage): ...
class SyncCommitteeMessageGnosis(SyncCommitteeMessage): ...

class SignedAggregateAndProof(SszObject):
    @property
    def message(self) -> projections.AggregateAndProof: ...
    @property
    def signature(self) -> bytes: ...

SignedAggregateAndProofMainnet = SignedAggregateAndProof

class SignedAggregateAndProofMinimal(SignedAggregateAndProof): ...
class SignedAggregateAndProofGnosis(SignedAggregateAndProof): ...

class SignedContributionAndProof(SszObject):
    @property
    def message(self) -> projections.ContributionAndProof: ...
    @property
    def signature(self) -> bytes: ...

SignedContributionAndProofMainnet = SignedContributionAndProof

class SignedContributionAndProofMinimal(SignedContributionAndProof): ...
class SignedContributionAndProofGnosis(SignedContributionAndProof): ...

class IndexedAttestation(SszObject):
    @property
    def attesting_indices(self) -> tuple[int, ...]: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...

IndexedAttestationMainnet = IndexedAttestation

class IndexedAttestationMinimal(IndexedAttestation): ...
class IndexedAttestationGnosis(IndexedAttestation): ...

class AttesterSlashing(SszObject):
    @property
    def attestation_1(self) -> projections.IndexedAttestation: ...
    @property
    def attestation_2(self) -> projections.IndexedAttestation: ...

AttesterSlashingMainnet = AttesterSlashing

class AttesterSlashingMinimal(AttesterSlashing): ...
class AttesterSlashingGnosis(AttesterSlashing): ...

class BeaconBlockHeader(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def proposer_index(self) -> int: ...
    @property
    def parent_root(self) -> bytes: ...
    @property
    def state_root(self) -> bytes: ...
    @property
    def body_root(self) -> bytes: ...

BeaconBlockHeaderMainnet = BeaconBlockHeader

class BeaconBlockHeaderMinimal(BeaconBlockHeader): ...
class BeaconBlockHeaderGnosis(BeaconBlockHeader): ...

class SignedBeaconBlockHeader(SszObject):
    @property
    def message(self) -> projections.BeaconBlockHeader: ...
    @property
    def signature(self) -> bytes: ...

SignedBeaconBlockHeaderMainnet = SignedBeaconBlockHeader

class SignedBeaconBlockHeaderMinimal(SignedBeaconBlockHeader): ...
class SignedBeaconBlockHeaderGnosis(SignedBeaconBlockHeader): ...

class ProposerSlashing(SszObject):
    @property
    def signed_header_1(self) -> projections.SignedBeaconBlockHeader: ...
    @property
    def signed_header_2(self) -> projections.SignedBeaconBlockHeader: ...

ProposerSlashingMainnet = ProposerSlashing

class ProposerSlashingMinimal(ProposerSlashing): ...
class ProposerSlashingGnosis(ProposerSlashing): ...
