"""Generated from spy_ssz/schemas.yaml; do not edit."""

from .. import projections
from ..ssz import SszObject

class SignedBeaconBlockElectra(SszObject):
    @property
    def message(self) -> projections.BeaconBlockElectra: ...
    @property
    def signature(self) -> bytes: ...

SignedBeaconBlockElectraMainnet = SignedBeaconBlockElectra

class SignedBeaconBlockElectraMinimal(SignedBeaconBlockElectra): ...
class SignedBeaconBlockElectraGnosis(SignedBeaconBlockElectra): ...

class BeaconBlockContentsElectra(SszObject):
    def header_dict(self) -> dict[str, str]: ...
    def block_hash_tree_root(self) -> str: ...
    def sign(self, signature: str | bytes) -> SignedBeaconBlockContentsElectra: ...
    @classmethod
    def signed_type(cls) -> type[SignedBeaconBlockContentsElectra]: ...

class SignedBeaconBlockContentsElectra(SszObject): ...

class BlindedBeaconBlockElectra(SszObject):
    def header_dict(self) -> dict[str, str]: ...
    def block_hash_tree_root(self) -> str: ...
    def sign(self, signature: str | bytes) -> SignedBlindedBeaconBlockElectra: ...
    @classmethod
    def signed_type(cls) -> type[SignedBlindedBeaconBlockElectra]: ...

class SignedBlindedBeaconBlockElectra(SszObject): ...
class SignedBeaconBlockContentsElectraMainnet(SignedBeaconBlockContentsElectra): ...

class BeaconBlockContentsElectraMainnet(BeaconBlockContentsElectra):
    def sign(
        self, signature: str | bytes
    ) -> SignedBeaconBlockContentsElectraMainnet: ...
    @classmethod
    def signed_type(cls) -> type[SignedBeaconBlockContentsElectraMainnet]: ...

class SignedBlindedBeaconBlockElectraMainnet(SignedBlindedBeaconBlockElectra): ...

class BlindedBeaconBlockElectraMainnet(BlindedBeaconBlockElectra):
    def sign(
        self, signature: str | bytes
    ) -> SignedBlindedBeaconBlockElectraMainnet: ...
    @classmethod
    def signed_type(cls) -> type[SignedBlindedBeaconBlockElectraMainnet]: ...

class SignedBeaconBlockContentsElectraMinimal(SignedBeaconBlockContentsElectra): ...

class BeaconBlockContentsElectraMinimal(BeaconBlockContentsElectra):
    def sign(
        self, signature: str | bytes
    ) -> SignedBeaconBlockContentsElectraMinimal: ...
    @classmethod
    def signed_type(cls) -> type[SignedBeaconBlockContentsElectraMinimal]: ...

class SignedBlindedBeaconBlockElectraMinimal(SignedBlindedBeaconBlockElectra): ...

class BlindedBeaconBlockElectraMinimal(BlindedBeaconBlockElectra):
    def sign(
        self, signature: str | bytes
    ) -> SignedBlindedBeaconBlockElectraMinimal: ...
    @classmethod
    def signed_type(cls) -> type[SignedBlindedBeaconBlockElectraMinimal]: ...

class SignedBeaconBlockContentsElectraGnosis(SignedBeaconBlockContentsElectra): ...

class BeaconBlockContentsElectraGnosis(BeaconBlockContentsElectra):
    def sign(
        self, signature: str | bytes
    ) -> SignedBeaconBlockContentsElectraGnosis: ...
    @classmethod
    def signed_type(cls) -> type[SignedBeaconBlockContentsElectraGnosis]: ...

class SignedBlindedBeaconBlockElectraGnosis(SignedBlindedBeaconBlockElectra): ...

class BlindedBeaconBlockElectraGnosis(BlindedBeaconBlockElectra):
    def sign(self, signature: str | bytes) -> SignedBlindedBeaconBlockElectraGnosis: ...
    @classmethod
    def signed_type(cls) -> type[SignedBlindedBeaconBlockElectraGnosis]: ...
