"""Generated from spy_ssz/schemas.yaml; do not edit."""

from .. import projections
from ..ssz import SszObject

class ElectraSignedBeaconBlock(SszObject):
    @property
    def message(self) -> projections.BeaconBlock: ...
    @property
    def signature(self) -> bytes: ...

ElectraSignedBeaconBlockMainnet = ElectraSignedBeaconBlock

class ElectraSignedBeaconBlockMinimal(ElectraSignedBeaconBlock): ...
class ElectraSignedBeaconBlockGnosis(ElectraSignedBeaconBlock): ...

class ElectraBeaconBlockContents(SszObject):
    def header_dict(self) -> dict[str, str]: ...
    def block_hash_tree_root(self) -> str: ...
    def sign(self, signature: str | bytes) -> ElectraSignedBeaconBlockContents: ...
    @classmethod
    def signed_type(cls) -> type[ElectraSignedBeaconBlockContents]: ...

class ElectraSignedBeaconBlockContents(SszObject): ...

class ElectraBlindedBeaconBlock(SszObject):
    def header_dict(self) -> dict[str, str]: ...
    def block_hash_tree_root(self) -> str: ...
    def sign(self, signature: str | bytes) -> ElectraSignedBlindedBeaconBlock: ...
    @classmethod
    def signed_type(cls) -> type[ElectraSignedBlindedBeaconBlock]: ...

class ElectraSignedBlindedBeaconBlock(SszObject): ...
class ElectraSignedBeaconBlockContentsMainnet(ElectraSignedBeaconBlockContents): ...

class ElectraBeaconBlockContentsMainnet(ElectraBeaconBlockContents):
    def sign(
        self, signature: str | bytes
    ) -> ElectraSignedBeaconBlockContentsMainnet: ...
    @classmethod
    def signed_type(cls) -> type[ElectraSignedBeaconBlockContentsMainnet]: ...

class ElectraSignedBlindedBeaconBlockMainnet(ElectraSignedBlindedBeaconBlock): ...

class ElectraBlindedBeaconBlockMainnet(ElectraBlindedBeaconBlock):
    def sign(
        self, signature: str | bytes
    ) -> ElectraSignedBlindedBeaconBlockMainnet: ...
    @classmethod
    def signed_type(cls) -> type[ElectraSignedBlindedBeaconBlockMainnet]: ...

class ElectraSignedBeaconBlockContentsMinimal(ElectraSignedBeaconBlockContents): ...

class ElectraBeaconBlockContentsMinimal(ElectraBeaconBlockContents):
    def sign(
        self, signature: str | bytes
    ) -> ElectraSignedBeaconBlockContentsMinimal: ...
    @classmethod
    def signed_type(cls) -> type[ElectraSignedBeaconBlockContentsMinimal]: ...

class ElectraSignedBlindedBeaconBlockMinimal(ElectraSignedBlindedBeaconBlock): ...

class ElectraBlindedBeaconBlockMinimal(ElectraBlindedBeaconBlock):
    def sign(
        self, signature: str | bytes
    ) -> ElectraSignedBlindedBeaconBlockMinimal: ...
    @classmethod
    def signed_type(cls) -> type[ElectraSignedBlindedBeaconBlockMinimal]: ...

class ElectraSignedBeaconBlockContentsGnosis(ElectraSignedBeaconBlockContents): ...

class ElectraBeaconBlockContentsGnosis(ElectraBeaconBlockContents):
    def sign(
        self, signature: str | bytes
    ) -> ElectraSignedBeaconBlockContentsGnosis: ...
    @classmethod
    def signed_type(cls) -> type[ElectraSignedBeaconBlockContentsGnosis]: ...

class ElectraSignedBlindedBeaconBlockGnosis(ElectraSignedBlindedBeaconBlock): ...

class ElectraBlindedBeaconBlockGnosis(ElectraBlindedBeaconBlock):
    def sign(self, signature: str | bytes) -> ElectraSignedBlindedBeaconBlockGnosis: ...
    @classmethod
    def signed_type(cls) -> type[ElectraSignedBlindedBeaconBlockGnosis]: ...
