"""Generated from spy_ssz/schemas.yaml; do not edit."""

from .. import projections
from ..ssz import Bitfield, SszObject

class SignedBeaconBlockGloas(SszObject):
    @property
    def message(self) -> projections.BeaconBlockGloas: ...
    @property
    def signature(self) -> bytes: ...

SignedBeaconBlockGloasMainnet = SignedBeaconBlockGloas

class SignedBeaconBlockGloasMinimal(SignedBeaconBlockGloas): ...
class SignedBeaconBlockGloasGnosis(SignedBeaconBlockGloas): ...

class BeaconBlockGloas(SszObject):
    def header_dict(self) -> dict[str, str]: ...
    def block_hash_tree_root(self) -> str: ...
    def sign(self, signature: str | bytes) -> SignedBeaconBlockGloas: ...
    @classmethod
    def signed_type(cls) -> type[SignedBeaconBlockGloas]: ...
    @property
    def slot(self) -> int: ...
    @property
    def proposer_index(self) -> int: ...
    @property
    def parent_root(self) -> bytes: ...
    @property
    def state_root(self) -> bytes: ...
    @property
    def body(self) -> projections.BeaconBlockBodyGloas: ...

BeaconBlockGloasMainnet = BeaconBlockGloas

class BeaconBlockGloasMinimal(BeaconBlockGloas):
    def sign(self, signature: str | bytes) -> SignedBeaconBlockGloasMinimal: ...
    @classmethod
    def signed_type(cls) -> type[SignedBeaconBlockGloasMinimal]: ...

class BeaconBlockGloasGnosis(BeaconBlockGloas):
    def sign(self, signature: str | bytes) -> SignedBeaconBlockGloasGnosis: ...
    @classmethod
    def signed_type(cls) -> type[SignedBeaconBlockGloasGnosis]: ...

class AttestationGloas(SszObject):
    @property
    def aggregation_bits(self) -> Bitfield: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...
    @property
    def committee_bits(self) -> Bitfield: ...

AttestationGloasMainnet = AttestationGloas

class AttestationGloasMinimal(AttestationGloas): ...
class AttestationGloasGnosis(AttestationGloas): ...

class AttestationDataGloas(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def index(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def source(self) -> projections.Checkpoint: ...
    @property
    def target(self) -> projections.Checkpoint: ...

AttestationDataGloasMainnet = AttestationDataGloas

class AttestationDataGloasMinimal(AttestationDataGloas): ...
class AttestationDataGloasGnosis(AttestationDataGloas): ...

class AggregateAndProofGloas(SszObject):
    @property
    def aggregator_index(self) -> int: ...
    @property
    def aggregate(self) -> projections.AttestationGloas: ...
    @property
    def selection_proof(self) -> bytes: ...

AggregateAndProofGloasMainnet = AggregateAndProofGloas

class AggregateAndProofGloasMinimal(AggregateAndProofGloas): ...
class AggregateAndProofGloasGnosis(AggregateAndProofGloas): ...

class SyncCommitteeContributionGloas(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def subcommittee_index(self) -> int: ...
    @property
    def aggregation_bits(self) -> Bitfield: ...
    @property
    def signature(self) -> bytes: ...

SyncCommitteeContributionGloasMainnet = SyncCommitteeContributionGloas

class SyncCommitteeContributionGloasMinimal(SyncCommitteeContributionGloas): ...
class SyncCommitteeContributionGloasGnosis(SyncCommitteeContributionGloas): ...

class ContributionAndProofGloas(SszObject):
    @property
    def aggregator_index(self) -> int: ...
    @property
    def contribution(self) -> projections.SyncCommitteeContribution: ...
    @property
    def selection_proof(self) -> bytes: ...

ContributionAndProofGloasMainnet = ContributionAndProofGloas

class ContributionAndProofGloasMinimal(ContributionAndProofGloas): ...
class ContributionAndProofGloasGnosis(ContributionAndProofGloas): ...

class SingleAttestationGloas(SszObject):
    @property
    def committee_index(self) -> int: ...
    @property
    def attester_index(self) -> int: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...

SingleAttestationGloasMainnet = SingleAttestationGloas

class SingleAttestationGloasMinimal(SingleAttestationGloas): ...
class SingleAttestationGloasGnosis(SingleAttestationGloas): ...

class SyncCommitteeMessageGloas(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def validator_index(self) -> int: ...
    @property
    def signature(self) -> bytes: ...

SyncCommitteeMessageGloasMainnet = SyncCommitteeMessageGloas

class SyncCommitteeMessageGloasMinimal(SyncCommitteeMessageGloas): ...
class SyncCommitteeMessageGloasGnosis(SyncCommitteeMessageGloas): ...

class SignedAggregateAndProofGloas(SszObject):
    @property
    def message(self) -> projections.AggregateAndProofGloas: ...
    @property
    def signature(self) -> bytes: ...

SignedAggregateAndProofGloasMainnet = SignedAggregateAndProofGloas

class SignedAggregateAndProofGloasMinimal(SignedAggregateAndProofGloas): ...
class SignedAggregateAndProofGloasGnosis(SignedAggregateAndProofGloas): ...

class SignedContributionAndProofGloas(SszObject):
    @property
    def message(self) -> projections.ContributionAndProof: ...
    @property
    def signature(self) -> bytes: ...

SignedContributionAndProofGloasMainnet = SignedContributionAndProofGloas

class SignedContributionAndProofGloasMinimal(SignedContributionAndProofGloas): ...
class SignedContributionAndProofGloasGnosis(SignedContributionAndProofGloas): ...

class IndexedAttestationGloas(SszObject):
    @property
    def attesting_indices(self) -> tuple[int, ...]: ...
    @property
    def data(self) -> projections.AttestationData: ...
    @property
    def signature(self) -> bytes: ...

IndexedAttestationGloasMainnet = IndexedAttestationGloas

class IndexedAttestationGloasMinimal(IndexedAttestationGloas): ...
class IndexedAttestationGloasGnosis(IndexedAttestationGloas): ...

class AttesterSlashingGloas(SszObject):
    @property
    def attestation_1(self) -> projections.IndexedAttestationGloas: ...
    @property
    def attestation_2(self) -> projections.IndexedAttestationGloas: ...

AttesterSlashingGloasMainnet = AttesterSlashingGloas

class AttesterSlashingGloasMinimal(AttesterSlashingGloas): ...
class AttesterSlashingGloasGnosis(AttesterSlashingGloas): ...

class BeaconBlockHeaderGloas(SszObject):
    @property
    def slot(self) -> int: ...
    @property
    def proposer_index(self) -> int: ...
    @property
    def parent_root(self) -> bytes: ...
    @property
    def state_root(self) -> bytes: ...
    @property
    def body_root(self) -> bytes: ...

BeaconBlockHeaderGloasMainnet = BeaconBlockHeaderGloas

class BeaconBlockHeaderGloasMinimal(BeaconBlockHeaderGloas): ...
class BeaconBlockHeaderGloasGnosis(BeaconBlockHeaderGloas): ...

class SignedBeaconBlockHeaderGloas(SszObject):
    @property
    def message(self) -> projections.BeaconBlockHeader: ...
    @property
    def signature(self) -> bytes: ...

SignedBeaconBlockHeaderGloasMainnet = SignedBeaconBlockHeaderGloas

class SignedBeaconBlockHeaderGloasMinimal(SignedBeaconBlockHeaderGloas): ...
class SignedBeaconBlockHeaderGloasGnosis(SignedBeaconBlockHeaderGloas): ...

class ProposerSlashingGloas(SszObject):
    @property
    def signed_header_1(self) -> projections.SignedBeaconBlockHeader: ...
    @property
    def signed_header_2(self) -> projections.SignedBeaconBlockHeader: ...

ProposerSlashingGloasMainnet = ProposerSlashingGloas

class ProposerSlashingGloasMinimal(ProposerSlashingGloas): ...
class ProposerSlashingGloasGnosis(ProposerSlashingGloas): ...

class PayloadAttestationDataGloas(SszObject):
    @property
    def beacon_block_root(self) -> bytes: ...
    @property
    def slot(self) -> int: ...
    @property
    def payload_present(self) -> bool: ...
    @property
    def blob_data_available(self) -> bool: ...

PayloadAttestationDataGloasMainnet = PayloadAttestationDataGloas

class PayloadAttestationDataGloasMinimal(PayloadAttestationDataGloas): ...
class PayloadAttestationDataGloasGnosis(PayloadAttestationDataGloas): ...

class PayloadAttestationGloas(SszObject):
    @property
    def aggregation_bits(self) -> Bitfield: ...
    @property
    def data(self) -> projections.PayloadAttestationData: ...
    @property
    def signature(self) -> bytes: ...

PayloadAttestationGloasMainnet = PayloadAttestationGloas

class PayloadAttestationGloasMinimal(PayloadAttestationGloas): ...
class PayloadAttestationGloasGnosis(PayloadAttestationGloas): ...

class PayloadAttestationMessageGloas(SszObject):
    @property
    def validator_index(self) -> int: ...
    @property
    def data(self) -> projections.PayloadAttestationData: ...
    @property
    def signature(self) -> bytes: ...

PayloadAttestationMessageGloasMainnet = PayloadAttestationMessageGloas

class PayloadAttestationMessageGloasMinimal(PayloadAttestationMessageGloas): ...
class PayloadAttestationMessageGloasGnosis(PayloadAttestationMessageGloas): ...

class ProposerPreferencesGloas(SszObject):
    @property
    def dependent_root(self) -> bytes: ...
    @property
    def proposal_slot(self) -> int: ...
    @property
    def validator_index(self) -> int: ...
    @property
    def fee_recipient(self) -> bytes: ...
    @property
    def target_gas_limit(self) -> int: ...

ProposerPreferencesGloasMainnet = ProposerPreferencesGloas

class ProposerPreferencesGloasMinimal(ProposerPreferencesGloas): ...
class ProposerPreferencesGloasGnosis(ProposerPreferencesGloas): ...

class SignedProposerPreferencesGloas(SszObject):
    @property
    def message(self) -> projections.ProposerPreferences: ...
    @property
    def signature(self) -> bytes: ...

SignedProposerPreferencesGloasMainnet = SignedProposerPreferencesGloas

class SignedProposerPreferencesGloasMinimal(SignedProposerPreferencesGloas): ...
class SignedProposerPreferencesGloasGnosis(SignedProposerPreferencesGloas): ...
