/* Generated from spy_ssz/schemas.yaml; do not edit. */
#ifndef SPY_SSZ_METADATA_CONSTANTS_H
#define SPY_SSZ_METADATA_CONSTANTS_H

#define SPY_SSZ_OBJECT_SIGNED_BEACON_BLOCK 1
#define SPY_SSZ_OBJECT_BEACON_BLOCK 2
#define SPY_SSZ_OBJECT_ATTESTATION 3
#define SPY_SSZ_OBJECT_ATTESTATION_DATA 4
#define SPY_SSZ_OBJECT_AGGREGATE_AND_PROOF 5
#define SPY_SSZ_OBJECT_SYNC_COMMITTEE_CONTRIBUTION 6
#define SPY_SSZ_OBJECT_CONTRIBUTION_AND_PROOF 7
#define SPY_SSZ_OBJECT_BEACON_BLOCK_CONTENTS 8
#define SPY_SSZ_OBJECT_SIGNED_BEACON_BLOCK_CONTENTS 9
#define SPY_SSZ_OBJECT_BLINDED_BEACON_BLOCK 10
#define SPY_SSZ_OBJECT_SIGNED_BLINDED_BEACON_BLOCK 11

#endif
